# Generated by Django 3.0.7 on 2020-06-28 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Question',
        ),
    ]
