# Generated by Django 3.0.7 on 2020-06-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20200629_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
